services:
  python-app:
    image: python:3.9-slim
    container_name: python
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install flask && python app.py"
    restart: unless-stopped
