services:
  nginx:
    image: nginx:latest
    container_name: nginx-teste
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # Mapeia a pasta atual do host para a pasta de arquivos do Nginx
      - /data/meu-teste-deploy/:/usr/share/nginx/html:ro
